### PR TITLE
[NumericInput] Improve placeholder

### LINKED ISSUE #1860: [NumericInput]: placeholder doesn't appear after removing value if min>0
## Description

If User sets that the minimum value in the numeric input is greater than 0, then after deleting entered value, the minimum set value is overwritten, instead of the placeholder.

## Steps to Reproduce

1. Open [NumericInput](https://uui.epam.com/documents?category=components&id=numericInput&mode=propsEditor&isSkin=true&theme=loveship) component.
2. Set property min=10.
3. Input any value in the numeric input example.
4. Delete the entered value.
5. Press `delete` button.

## Actual result

The set minimum value appears instead of the placeholder.

https://github.com/epam/UUI/assets/57751283/e0a08a28-c10d-4afe-bdc4-9950f232e885

## Expected result

Placeholder appears.

## Environment

* UUI version: 5.4.2
* Browser name: any
* Operating System: any

### PR DESCRIPTION
**Pull request by dimaanj**
## Summary

- Fixes #1860
- Improves null checks

### CODE REVIEW

File: uui-components/src/inputs/NumericInput.tsx [hunk 1]
```diff
@@ -77,19 +77,28 @@ const getFractionDigits = (formatOptions: Intl.NumberFormatOptions) => {
...
+    const value = initialValue != null ? +initialValue : null;
+    const min = initialMin ?? 0;
+    const max = initialMax ?? Number.MAX_SAFE_INTEGER;
+    const formatOptions = initialFormatOptions ?? { maximumFractionDigits: 0 };
 
-    if (value != null) {
-        value = +value;
-    }
+    const placeholderValue = React.useMemo(() => {
+        if (!value && value !== 0) return props.placeholder || '0';
```
Comment (AlekseyManetov) [inline uui-components/src/inputs/NumericInput.tsx:95]: Probably we can rewrite this condition to more straightforward: `if (value === null || value === undefined)`?

File: uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx [hunk 2]
```diff
@@ -29,7 +35,6 @@ describe('numericInputCalculations', () => {
         expect(getMinMaxValidatedValue({ value: 10, min: 0, max: 10 })).toBe(10);
         expect(getMinMaxValidatedValue({ value: 12, min: 0, max: 10 })).toBe(10);
         expect(getMinMaxValidatedValue({ value: -1, max: 10 })).toBe(0);
-        expect(getMinMaxValidatedValue({ value: null, max: 10 })).toBe(null);
```
Comment (AlekseyManetov) [inline uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx:32]: why do we remove this case?

**Review by AlekseyManetov — CHANGES_REQUESTED** [review]

File: uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx (hunk 2 above)
Comment (dimaanj) [reply uui-core/src/helpers/__tests__/numericInputCalculations.test.tsx:32]: ValidationDTO interface accept only `value: number`.
